[package]
name = "p77-render-hex-functional"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
turtle = "^1.0.0-rc.3"
svg = "0.10"