[package]
name = "p52-particles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.123"
piston2d-graphics = "0.42"
rand = "0.8"
